# Generated by Django 4.0.4 on 2022-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_status'),
        ('users', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='blog.post'),
        ),
    ]
