# Generated by Django 4.0.4 on 2022-05-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='C:\\Users\\user\\PycharmProjects\\blog_site\\media\\dafault_post.jpg', upload_to='post-date-(%Y-%m-%d)/'),
        ),
    ]
